"""add looking_for_gender

Revision ID: 563048c45fba
Revises: 0e2632f4b3f2
Create Date: 2026-05-06 17:33:29.173643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563048c45fba'
down_revision = '0e2632f4b3f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('looking_for_gender', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('looking_for_gender')

    # ### end Alembic commands ###
