"""empty message

Revision ID: 6e31865d5952
Revises: 
Create Date: 2026-04-29 13:09:33.687451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e31865d5952'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('profile_picture',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('profile_pic', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('profile_visibility',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('visibility', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('user_bio',
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('fname', sa.String(length=60), nullable=False),
    sa.Column('lname', sa.String(length=60), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('email')
    )
    op.create_table('interests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('interest', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('interest')
    )
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_user', sa.String(length=80), nullable=False),
    sa.Column('Suggested_user', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['Suggested_user'], ['users.username'], ),
    sa.ForeignKeyConstraint(['target_user'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter', sa.String(length=80), nullable=False),
    sa.Column('reported_user', sa.String(length=80), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reported_user'], ['users.username'], ),
    sa.ForeignKeyConstraint(['reporter'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1', sa.String(length=80), nullable=False),
    sa.Column('user2', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['likes.id'], ),
    sa.ForeignKeyConstraint(['user1'], ['users.username'], ),
    sa.ForeignKeyConstraint(['user2'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('sender_name', sa.String(length=80), nullable=False),
    sa.Column('reciever_name', sa.String(length=80), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['reciever_name'], ['users.username'], ),
    sa.ForeignKeyConstraint(['sender_name'], ['users.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('matches')
    op.drop_table('reports')
    op.drop_table('likes')
    op.drop_table('interests')
    op.drop_table('users')
    op.drop_table('user_bio')
    op.drop_table('profile_visibility')
    op.drop_table('profile_picture')
    op.drop_table('location')
    # ### end Alembic commands ###
