"""add profile views

Revision ID: 909fffdf1053
Revises: 563048c45fba
Create Date: 2026-05-06 18:12:43.525644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '909fffdf1053'
down_revision = '563048c45fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_views', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('profile_views')

    # ### end Alembic commands ###
