"""empty message

Revision ID: c5f28cca8b29
Revises: a2636c37aa5e
Create Date: 2026-05-02 07:37:24.474473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f28cca8b29'
down_revision = 'a2636c37aa5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'profile_id', name='unique_favorite')
    )
    op.drop_table('profile_interests')
    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('interest', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(batch_op.f('interests_name_key'), type_='unique')
        batch_op.create_unique_constraint('unique_user_interest', ['user_id', 'interest'])
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.drop_column('name')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('to_user_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('unique_like', ['from_user_id', 'to_user_id'])
        batch_op.drop_constraint(batch_op.f('likes_liked_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('likes_liker_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['to_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['from_user_id'], ['id'])
        batch_op.drop_column('action')
        batch_op.drop_column('liked_id')
        batch_op.drop_column('liker_id')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_match', ['user1_id', 'user2_id'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('to_user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('messages_sender_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['from_user_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['to_user_id'], ['id'])
        batch_op.drop_column('sender_id')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('occupation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('zodiac_sign', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('preferred_location_radius', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('preferred_age_min', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('preferred_age_max', sa.Integer(), nullable=True))
        batch_op.alter_column('location',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['user_id'])
        batch_op.drop_column('gender')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('last_name')
        batch_op.drop_column('looking_for')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('fname', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('lname', sa.String(length=60), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=1), nullable=False))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('gender')
        batch_op.drop_column('lname')
        batch_op.drop_column('fname')
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('looking_for', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('location',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.drop_column('preferred_age_max')
        batch_op.drop_column('preferred_age_min')
        batch_op.drop_column('preferred_location_radius')
        batch_op.drop_column('zodiac_sign')
        batch_op.drop_column('occupation')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('messages_sender_id_fkey'), 'users', ['sender_id'], ['id'])
        batch_op.drop_column('to_user_id')
        batch_op.drop_column('from_user_id')

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint('unique_match', type_='unique')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liker_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('liked_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('action', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('likes_liker_id_fkey'), 'users', ['liker_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('likes_liked_id_fkey'), 'users', ['liked_id'], ['id'])
        batch_op.drop_constraint('unique_like', type_='unique')
        batch_op.drop_column('to_user_id')
        batch_op.drop_column('from_user_id')

    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint('unique_user_interest', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('interests_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('interest')
        batch_op.drop_column('user_id')

    op.create_table('profile_interests',
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interest_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], name=op.f('profile_interests_interest_id_fkey')),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('profile_interests_profile_id_fkey')),
    sa.PrimaryKeyConstraint('profile_id', 'interest_id', name=op.f('profile_interests_pkey'))
    )
    op.drop_table('favorites')
    # ### end Alembic commands ###
